config/routes.rb
Rails.application.routes.draw do
  resources :books do
    collection do
      get :search
    end
    resources :reviews, only: :create
  end
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :reviews

  def self.search(query)
    where('title LIKE :query or content LIKE :query', query: "%#{query}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  validates :rating, presence: true, numericality: { greater_than_or_equal_to: 1,
                                                     less_than_or_equal_to: 5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.search(params[:query]).reverse
  end

  # GET /books/1 or /books/1.json
  def show
    @reviews = @book.reviews.reverse
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def show
  end

  def new
  end

  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.new(review_params)

    if @review.save
      redirect_to book_path(@book), notice: "Review submitted successfully"
    else
      render :new
    end
  end

  def destroy
  end

  private

  def review_params
    params.permit(:rating, :content, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <h2>
    <strong>Title:</strong>
    <%= book.title %>
  </h2>

  <p>
    <strong>Content:</strong>
    <%= book.content %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %>
        prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_review_form.html.erb
<%= form_with url: book_reviews_path(@book), method: :post do |f| %>
  <div>
    <%= f.label :rating, "Rating:", style: "display: block" %>
    <%= f.select :rating, (1..5).to_a %>
  </div>
  <div>
    <%= f.label :content, "Content:", style: "display: block" %>
    <%= f.text_field :content %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_reviews_list.html.erb
<% @reviews.each do |review| %>
  <div>
    <p>Rating:
      <%= review.rating %></p>
    <p>Content:
      <%= review.content %></p>
  </div>
  <hr>
<% end %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Books" %>

<h1>Books</h1>

<%= form_with remote: true, method: :get do |f| %>
  <div id="search-box">
    <%= f.text_field :query, placeholder: "Search for:" %>
  </div>
<% end %>

<br>

<%= turbo_frame_tag "new_book" do %>
  <div>
    <%= link_to "New book", new_book_path %>
  </div>
<% end %>

<br>

<%= turbo_frame_tag "books_list" do %>
  <div id="books">
    <% @books.each do |book| %>
      <%= turbo_frame_tag book do %>
        <%= render book %>
        <p>
          <%= link_to "Details", book %>
        </p>
      <% end %>

      <br>

    <% end %>
  </div>
<% end %>

app/views/books/new.html.erb
<% content_for :title, "New book" %>

<h1>New book</h1>

<%= turbo_frame_tag "new_book" do %>
  <%= render "form", book: @book %>

  <br>

  <div>
    <%= link_to "Back", books_path %>
  </div>
<% end %>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag @book do %>
  <%= render @book %>

  <div>
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Back", books_path %>
    <%= button_to "Destroy", @book, method: :delete %>
  </div>

  <div>
    <h3>Reviews</h3>
    <%= render "reviews_list" %>
    <%= render "review_form" %>
  </div>
<% end %>

app/views/home/index.html.erb
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<div class="container-flouid">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">
        <h3>Review Books</h3>
      </a>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Review Books" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>